vouch:
  testing: true
  logLevel: debug
  listen: 0.0.0.0
  port: 9090

  allowAllUsers: true

  headers:
    claims:
      - groups
      - boolean_claim
      - family_name
      - http://www.example.com/favorite_color

  cookie:
    name: vouchTestingCookie

  session:
    name: VouchTestingSession

  jwt:
    secret: testing

oauth:
  provider: indieauth
  client_id: http://vouch.github.io
  auth_url: https://indielogin.com/auth
  callback_url: http://vouch.github.io:9090/auth
